/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'

export const postsMap = {
  'hello-world': {
    id: 0,
    slug: 'hello-world',

    component: /*#__PURE__*/ React.lazy(() => import('./0-hello-world.mdx')),
    metadata: {
      title: 'Hello world',
      description: 'Add a reading time to my metadata please!',
      timestamp: 1597889187126,
      tags: [],
      categories: [],
      readingTime: {text: '3 min read', time: 123900, words: 413},
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
